### ISSUE TITLE
add API to RAIS for clearing cache

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#84] opened 2018-11-13 22:00 UTC
RAIS, our IIIF server, caches images from S3 onto disk, and may optionally be caching image tiles in memory.  When things change in Oregon Digital, we're going to want to make sure these caches get cleared so old images aren't showing up in the views.

**Comment by jechols** [comment] 2018-11-13 22:09
See https://github.com/uoregon-libraries/rais-image-server/issues/15 - this is in progress and should be ready soon.  (It's code-complete but still needs a little bit of testing)

**Comment by vantuyls** [comment] 2018-12-14 18:58
@jechols @decimalator so, without a description on this issue, it is not clear to me what the issue is for. clarification please

**Comment by jechols** [comment] 2018-12-14 19:46
Closing this issue.  Testing of *RAIS* wouldn't make sense in OD-land, so what we need is a new ticket for getting the purge calls in.  **That** ticket would be the one we'd test.

**Closed by jechols** 2018-12-14 19:46 UTC
Labels: Infrastructure
