### ISSUE TITLE
[A11y] Desktop/Mobile Collection Landing: Info Icon

### ISSUE THREAD

**Issue by azle** [OregonDigital/OD2#1750] opened 2021-08-03 15:36 UTC
### Operating System

MacOS

### Browser

Chrome

### Affected page

Collection Show

### Admin user?

- [ ] Yes

### Issue Description

Collection Landing: https://staging.oregondigital.org/collections/gwilliams?locale=en

The institution text link has a info icon next to it. The info icon needs an aria label describing where it is taking the user.

### Suggested Fix

Add an aria label with a description of where the link is going to take the user.

Note:
Should take you to the source of the URI in a new tab (or window, depending on one's browser setting), in this case the Library of Congress authority record

**Comment by CGillen** [comment] 2021-08-24 15:50
@thornka this is a duplicate of #1870. That ticket has a few more suggestions to fix this issue

**Closed** 2022-01-05 16:57 UTC
Labels: Features, Accessibility
