### ISSUE TITLE
Generate and config Generic work type

### ISSUE THREAD

**Issue by zhang4952** [OregonDigital/OD2#87] opened 2018-11-13 22:25 UTC
### Descriptive summary

We need to generate files for `Generic` work type for OD2 using a rake task command provided by Hyrax, and customize the generated files based on OD2 MAP (https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0)
- actor
- controller
- indexer
- forms
- presenters
- models
- views
- config
- spec

### Expected behavior

Create the files of `Generic` work type should be straightforward. The customization/configuration of created files could require quite some efforts. 

### Related work

OD2 MAP: https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0

Link to related tickets or prior related work here.
#21 
#27 

### Steps

- [x] Generate files with Hyrax rake task

- [x] Check the completeness of MAP with `Generic`

- [x] Configure `Generic` files with metadata fields

**Comment by luisgreg99** [comment] 2018-11-14 01:15
@zhang4952 It looks like the first step (rake task to generate default files such as model, controller, actors) for both Generic and Image models has been covered by https://github.com/OregonDigital/OD2/pull/67 I think we can built up on those files to extend or customize the metadata.

**Comment by zhang4952** [comment] 2018-11-16 04:05
#103

**Comment by revgum** [comment] 2018-12-04 15:54
Has this been completed @zhang4952 @straleyb

**Comment by zhang4952** [comment] 2018-12-04 17:12
I think it has been merged and in `QA` status now.

**Comment by wickr** [comment] 2018-12-11 01:50
Addressed by #129 and partly #153

**Comment by wickr** [comment] 2018-12-11 01:55
QA Issues from #129 

- [ ] :license in Generic metadata twice - Remove  property :license, predicate: ::RDF::Vocab::CC.License
- [ ] :source in Generic metadata twice - Remove 1st occurrence
- [ ] :has_part in Generic metadata twice - Remove 2nd occurrence (with :facetable)
- [ ] :has_part in PROPERTIES twice
- [ ] SpecimenType can use '_' in property name
- [ ] :identification_verification_status in PROPERTIES twice
- [ ] capitalized 'O' in predicate: property :identification_verification_status, predicate: ::RDF::Vocab::DWC.identificationVerificatiOnStatus
- [ ] :creator not in PROPERTIES
- [ ] :contributor not in PROPERTIES
- [ ] :description not in PROPERTIES
- [ ] :rights_statement not in PROPERTIES
- [ ] :identifier not in PROPERTIES
- [ ] :owner does not need 'multiple: false'
- [ ] Remove :date_created - duplicate of :created
- [ ] Remove :related_url
- [ ] Remove :bibliographic_citation - duplicate of :citation
- [ ] Remove :keyword
- [ ] Change current :subject to :keyword
- [ ] Change :lc_subject to :subject
- [ ] description should be ::RDF::Vocab::DC.description

**Comment by wickr** [comment] 2018-12-20 21:33
QA OK with #216

**Closed** 2018-12-29 00:38 UTC
Labels: Configuration
