### ISSUE TITLE
Install blazegraph and copy over configuration files for blazegraph

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#69] opened 2018-11-13 17:56 UTC
### Descriptive summary

This ticket describes the need for installing blazegraph for OD2. Blazegraph is handled mostly by the gem found here. https://github.com/osulp/triplestore-adapter

This gem is an interface gem which allows a user to connect to any triplestore backend like marmotta or in our case, blazegraph. By installing this gem, it gives you access to rake tasks which allow for the controlling of said backend triplestore. 

After the installation of this gem run the task `rake triplestore_adapter:blazegraph:setup` and this should setup any necessary configuration for the triplestore. 

You will know this is all working when you run `rake triplestore_adapter:blazegraph:start` and it works. 

One note is that in order for blazegraph to work, it needs a namespace. Im not entirely sure whether or not the namespace is built on configuration but you can also run `rake triplestore_adapter:blazegraph:build_namespace`

**Comment by decimalator** [comment] 2018-11-13 20:23
This is a duplicate of #33 which has more detail.

**Comment by straleyb** [comment] 2018-11-14 17:17
Reopening new ticket

**Closed** 2018-11-14 17:16 UTC

**Comment by revgum** [comment] 2018-11-16 12:43
fixed by #101
