### ISSUE TITLE
Number of items in collection on explore collections page displays 10 max

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1553] opened 2021-03-16 22:21 UTC
### Descriptive summary

This needs to display the max amount of works. For instance there is one on staging with 54 works but it still only displays 10.

**Comment by CGillen** [comment] 2021-04-23 21:59
Duplicate of #1533, that one has more information so closing this ticket.

**Closed by CGillen** 2021-04-23 21:59 UTC
Labels: Bug, Features, Ready for Development
