### ISSUE TITLE
Write print.css (for contribution to Hyrax as well).

### ISSUE THREAD

**Issue by mccallum** [OregonDigital/OD2#223] opened 2018-12-18 15:59 UTC
### Descriptive summary

Occasionally, users will want to print out an item and its metadata to PDF or hard copy. 

### Expected behavior

Printed page should appear with an expected visual hierarchy.

### Related work

Work in this print.css area could find its way to the Samvera community and the Hyrax code.

**Comment by raybrarian** [comment] 2019-10-08 16:39
Closed - duplicate of #646

**Closed by raybrarian** 2019-10-08 16:39 UTC
Labels: Design Needed, Priority - Low, UX
